<script lang="ts">
	import { setContext, type Snippet } from 'svelte';
	import { tv } from 'tailwind-variants';
	import deepmerge from 'deepmerge';
	import {
		accordion,
		accordionitem,
		alert,
		avatar,
		badge,
		banner,
		bottomNav,
		bottomNavItem,
		bottomnavheader,
		bottomnavheaderitem,
		breadcrumb,
		buttonGroup,
		button,
		gradientButton,
		card,
		darkmode,
		android,
		defaultMockup,
		desktop,
		ios,
		laptop,
		smartwatch,
		tablet,
		drawer,
		drawerhead,
		dropdown,
		dropdowndivider,
		dropdownli,
		dropdownul,
		dropdownHeader,
		dropdownFooter,
		footer,
		footerBrand,
		footerCopyright,
		footerIcon,
		footerUl,
		footerLi,
		gallery,
		indicator,
		kbd,
		listGroup,
		listGroupItem,
		megamenu,
		modal,
		navbar,
		navUl,
		navbrand,
		navLi,
		navhamburger,
		paginationItem,
		pagination,
		popover,
		progressbar,
		advancedrating,
		rating,
		review,
		scorerating,
		sidebar,
		sidebarbutton,
		sidebarcta,
		sitebarbrand,
		sidebardropdownwrapper,
		cardPlaceholder,
		imagePlaceholder,
		listPlaceholder,
		skeleton,
		testimonialPlaceholder,
		textPlaceholder,
		videoPlaceholder,
		widgetPlaceholder,
		spinner,
		table,
		tablebodyrow,
		tablehead,
		tablebodycell,
		tableheadcell,
		tabs,
		tabItem,
		activity,
		activityitem,
		group,
		groupitem,
		timeline,
		timelineitem,
		toast,
		toolbar,
		toolbarGroup,
		toolbarButton,
		tooltip,
		checkbox,
		dropzone,
		fileupload,
		floatingLabelInput,
		helper,
		input,
		label,
		radio,
		radioButton,
		range,
		search,
		select,
		textarea,
		toggle,
		anchor,
		blockquote,
		descriptionList,
		heading,
		hr,
		img,
		layout,
		list,
		mark,
		paragraph,
		secondary,
		span
	} from '$lib';

	interface Props {
		children: Snippet;
		theme?: Record<string, any>;
	}

	let { children, theme }: Props = $props();

	// Function to merge theme configurations
	function mergeThemes(baseThemes: Record<string, any>, customTheme?: Record<string, any>) {
		const mergedTheme: Record<string, any> = {};

		// Merge each component's theme
		for (const [componentName, baseTheme] of Object.entries(baseThemes)) {
			const customComponentTheme = customTheme?.[componentName] || {};

			// Deep merge base theme with custom theme
			mergedTheme[componentName] = tv(
				deepmerge(
					{
						slots: baseTheme.slots,
						variants: baseTheme.variants,
						compoundVariants: baseTheme.compoundVariants,
						defaultVariants: baseTheme.defaultVariants
					},
					{
						slots: customComponentTheme.slots || {},
						variants: customComponentTheme.variants || {},
						compoundVariants: customComponentTheme.compoundVariants || [],
						defaultVariants: customComponentTheme.defaultVariants || {}
					}
				)
			);
		}

		return mergedTheme;
	}

	const baseThemes = {
		accordion,
		accordionitem,
		alert,
		avatar,
		badge,
		banner,
		bottomNav,
		bottomNavItem,
		bottomnavheader,
		bottomnavheaderitem,
		breadcrumb,
		buttonGroup,
		button,
		gradientButton,
		card,
		darkmode,
		android,
		defaultMockup,
		desktop,
		ios,
		laptop,
		smartwatch,
		tablet,
		drawer,
		drawerhead,
		dropdown,
		dropdowndivider,
		dropdownli,
		dropdownul,
		dropdownHeader,
		dropdownFooter,
		footer,
		footerBrand,
		footerCopyright,
		footerIcon,
		footerUl,
		footerLi,
		gallery,
		indicator,
		kbd,
		listGroup,
		listGroupItem,
		megamenu,
		modal,
		navbar,
		navUl,
		navbrand,
		navLi,
		navhamburger,
		paginationItem,
		pagination,
		popover,
		progressbar,
		advancedrating,
		rating,
		review,
		scorerating,
		sidebar,
		sidebarbutton,
		sidebarcta,
		sitebarbrand,
		sidebardropdownwrapper,
		cardPlaceholder,
		imagePlaceholder,
		listPlaceholder,
		skeleton,
		testimonialPlaceholder,
		textPlaceholder,
		videoPlaceholder,
		widgetPlaceholder,
		spinner,
		table,
		tablebodyrow,
		tablehead,
		tablebodycell,
		tableheadcell,
		tabs,
		tabItem,
		activity,
		activityitem,
		group,
		groupitem,
		timeline,
		timelineitem,
		toast,
		toolbar,
		toolbarGroup,
		toolbarButton,
		tooltip,
		checkbox,
		dropzone,
		fileupload,
		floatingLabelInput,
		helper,
		input,
		label,
		radio,
		radioButton,
		range,
		search,
		select,
		textarea,
		toggle,
		anchor,
		blockquote,
		descriptionList,
		heading,
		hr,
		img,
		layout,
		list,
		mark,
		paragraph,
		secondary,
		span
	};

	const mergedThemes = mergeThemes(baseThemes, theme);

	setContext('themeConfig', mergedThemes);
</script>

{@render children()}

