const purebasic = `<style>pre code.hljs{display:block;overflow-x:auto;padding:1em}code.hljs{padding:3px 5px}.hljs{background:#FFFFDF}.hljs,
.hljs-type,
.hljs-function,
.hljs-name,
.hljs-number,
.hljs-attr,
.hljs-params,
.hljs-subst{color:#000000}.hljs-comment,
.hljs-regexp,
.hljs-section,
.hljs-selector-pseudo,
.hljs-addition{color:#00AAAA}.hljs-keyword,
.hljs-class,
.hljs-meta .hljs-keyword,
.hljs-selector-class,
.hljs-built_in{color:#006666;font-weight:bold}.hljs-title,
.hljs-tag,
.hljs-variable,
.hljs-code{color:#006666}.hljs-string,
.hljs-selector-attr{color:#0080FF}.hljs-symbol,
.hljs-link,
.hljs-deletion,
.hljs-attribute{color:#924B72}.hljs-meta,
.hljs-literal,
.hljs-selector-id{color:#924B72;font-weight:bold}.hljs-strong,
.hljs-name{font-weight:bold}.hljs-emphasis{font-style:italic}</style>`;

export default purebasic;
