name: "\U0001F41E Bug report"
description: Report an issue
labels: ['triage: bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide code or a link to a repo that can reproduce the problem you ran into. Use [Stackblitz](https://stackblitz.com/) to add your code. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided within a reasonable time-frame, the issue will be closed.
      placeholder: Repo, Stackblitz, demo.
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: Version and System Info
      description: Output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,svelte-5-ui-lib,vite,rollup,webpack --binaries --browsers`
      render: shell
      placeholder: Version, System, Binaries, Browsers
    validations:
      required: true
