name: "\U0001F41E Bug report"
description: Report an issue with Flowbite-Svelte
labels: ['triage: bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link to a repo or REPL that can reproduce the problem you ran into. Use [this Stackblitz template](https://stackblitz.com/edit/sveltejs-kit-template-default-efqgaq) or [Flowbite-Svelte template](https://svelte.dev/repl/930d39fbd10b4e5b8581fb20d3a3192e) to add your code. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "need reproduction" label. If no reproduction is provided within a reasonable time-frame, the issue will be closed.
      placeholder: REPL
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: Flowbite version and System Info
      description: Output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,flowbite-svelte,vite,rollup,webpack --binaries --browsers`
      render: shell
      placeholder: Version, System, Binaries, Browsers
    validations:
      required: true
