name: "\U0001F41E Bug report"
description: Report an issue with Flowbite-Svelte
labels: ["triage: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: |
        Please provide a **minimal code example** that demonstrates the problem. This should be self-contained, minimal, and runnable.
        
        Include:
        - What you expected to happen
        - What actually happens instead
        - Complete code example (copy/paste ready)
        - Any specific steps to trigger the issue
        
        Issues with vague descriptions and no reproduction code will receive a "needs reproduction" label and may be closed if not provided within a reasonable timeframe.
      placeholder: "Provide your minimal code example here..."
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: Version and System Info
      description: Output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,flowbite-svelte,vite,rollup,webpack --binaries --browsers`
      render: shell
      placeholder: Version, System, Binaries, Browsers
    validations:
      required: true
